package com.repository;

import com.entity.Chain_optimization;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Chain_optimization Repository
 * Generated by CoderAgent
 */
@Repository
public interface Chain_optimizationRepository extends JpaRepository<Chain_optimization, Long> {
    
}