package com.repository;

import com.entity.Optimization_record;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Optimization_record Repository
 * Generated by CoderAgent
 */
@Repository
public interface Optimization_recordRepository extends JpaRepository<Optimization_record, Long> {
    
}