package com.repository;

import com.entity.Users;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Users Repository
 * Generated by CoderAgent
 */
@Repository
public interface UsersRepository extends JpaRepository<Users, Long> {
    
}